#pragma once
#include "Objects.g.h"

using namespace System;

namespace Ctp
{
    namespace Net
    {
        public delegate void OnErrRtnBankToFutureByFuture(ReqTransferField^ reqTransfer, RspInfoField^ rspInfo);
        public delegate void OnErrRtnBatchOrderAction(BatchOrderActionField^ batchOrderAction, RspInfoField^ rspInfo);
        public delegate void OnErrRtnCombActionInsert(InputCombActionField^ inputCombAction, RspInfoField^ rspInfo);
        public delegate void OnErrRtnExecOrderAction(ExecOrderActionField^ execOrderAction, RspInfoField^ rspInfo);
        public delegate void OnErrRtnExecOrderInsert(InputExecOrderField^ inputExecOrder, RspInfoField^ rspInfo);
        public delegate void OnErrRtnForQuoteInsert(InputForQuoteField^ inputForQuote, RspInfoField^ rspInfo);
        public delegate void OnErrRtnFutureToBankByFuture(ReqTransferField^ reqTransfer, RspInfoField^ rspInfo);
        public delegate void OnErrRtnOptionSelfCloseAction(OptionSelfCloseActionField^ optionSelfCloseAction, RspInfoField^ rspInfo);
        public delegate void OnErrRtnOptionSelfCloseInsert(InputOptionSelfCloseField^ inputOptionSelfClose, RspInfoField^ rspInfo);
        public delegate void OnErrRtnOrderAction(OrderActionField^ orderAction, RspInfoField^ rspInfo);
        public delegate void OnErrRtnOrderInsert(InputOrderField^ inputOrder, RspInfoField^ rspInfo);
        public delegate void OnErrRtnQueryBankBalanceByFuture(ReqQueryAccountField^ reqQueryAccount, RspInfoField^ rspInfo);
        public delegate void OnErrRtnQuoteAction(QuoteActionField^ quoteAction, RspInfoField^ rspInfo);
        public delegate void OnErrRtnQuoteInsert(InputQuoteField^ inputQuote, RspInfoField^ rspInfo);
        public delegate void OnErrRtnRepealBankToFutureByFutureManual(ReqRepealField^ reqRepeal, RspInfoField^ rspInfo);
        public delegate void OnErrRtnRepealFutureToBankByFutureManual(ReqRepealField^ reqRepeal, RspInfoField^ rspInfo);
        public delegate void OnFrontConnected();
        public delegate void OnFrontDisconnected(int reason);
        public delegate void OnHeartBeatWarning(int timeLapse);
        public delegate void OnRspAuthenticate(RspAuthenticateField^ rspAuthenticateField, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspBatchOrderAction(InputBatchOrderActionField^ inputBatchOrderAction, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspCombActionInsert(InputCombActionField^ inputCombAction, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspError(RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspExecOrderAction(InputExecOrderActionField^ inputExecOrderAction, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspExecOrderInsert(InputExecOrderField^ inputExecOrder, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspForQuoteInsert(InputForQuoteField^ inputForQuote, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspFromBankToFutureByFuture(ReqTransferField^ reqTransfer, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspFromFutureToBankByFuture(ReqTransferField^ reqTransfer, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspGenUserCaptcha(RspGenUserCaptchaField^ rspGenUserCaptcha, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspGenUserText(RspGenUserTextField^ rspGenUserText, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspOptionSelfCloseAction(InputOptionSelfCloseActionField^ inputOptionSelfCloseAction, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspOptionSelfCloseInsert(InputOptionSelfCloseField^ inputOptionSelfClose, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspOrderAction(InputOrderActionField^ inputOrderAction, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspOrderInsert(InputOrderField^ inputOrder, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspParkedOrderAction(ParkedOrderActionField^ parkedOrderAction, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspParkedOrderInsert(ParkedOrderField^ parkedOrder, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryAccountregister(AccountregisterField^ accountregister, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryBrokerTradingAlgos(BrokerTradingAlgosField^ brokerTradingAlgos, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryBrokerTradingParams(BrokerTradingParamsField^ brokerTradingParams, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryCFMMCTradingAccountKey(CFMMCTradingAccountKeyField^ cFMMCTradingAccountKey, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryCombAction(CombActionField^ combAction, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryCombInstrumentGuard(CombInstrumentGuardField^ combInstrumentGuard, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryContractBank(ContractBankField^ contractBank, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryDepthMarketData(DepthMarketDataField^ depthMarketData, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryEWarrantOffset(EWarrantOffsetField^ eWarrantOffset, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryExchange(ExchangeField^ exchange, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryExchangeMarginRate(ExchangeMarginRateField^ exchangeMarginRate, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryExchangeMarginRateAdjust(ExchangeMarginRateAdjustField^ exchangeMarginRateAdjust, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryExchangeRate(ExchangeRateField^ exchangeRate, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryExecOrder(ExecOrderField^ execOrder, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryForQuote(ForQuoteField^ forQuote, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryInstrument(InstrumentField^ instrument, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryInstrumentCommissionRate(InstrumentCommissionRateField^ instrumentCommissionRate, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryInstrumentMarginRate(InstrumentMarginRateField^ instrumentMarginRate, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryInstrumentOrderCommRate(InstrumentOrderCommRateField^ instrumentOrderCommRate, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryInvestor(InvestorField^ investor, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryInvestorPosition(InvestorPositionField^ investorPosition, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryInvestorPositionCombineDetail(InvestorPositionCombineDetailField^ investorPositionCombineDetail, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryInvestorPositionDetail(InvestorPositionDetailField^ investorPositionDetail, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryInvestorProductGroupMargin(InvestorProductGroupMarginField^ investorProductGroupMargin, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryInvestUnit(InvestUnitField^ investUnit, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryMMInstrumentCommissionRate(MMInstrumentCommissionRateField^ mMInstrumentCommissionRate, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryMMOptionInstrCommRate(MMOptionInstrCommRateField^ mMOptionInstrCommRate, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryMulticastInstrument(MulticastInstrumentField^ multicastInstrument, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryNotice(NoticeField^ notice, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryOptionInstrCommRate(OptionInstrCommRateField^ optionInstrCommRate, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryOptionInstrTradeCost(OptionInstrTradeCostField^ optionInstrTradeCost, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryOptionSelfClose(OptionSelfCloseField^ optionSelfClose, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryOrder(OrderField^ order, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryParkedOrder(ParkedOrderField^ parkedOrder, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryParkedOrderAction(ParkedOrderActionField^ parkedOrderAction, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryProduct(ProductField^ product, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryProductExchRate(ProductExchRateField^ productExchRate, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryProductGroup(ProductGroupField^ productGroup, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryQuote(QuoteField^ quote, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQrySecAgentACIDMap(SecAgentACIDMapField^ secAgentACIDMap, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQrySecAgentCheckMode(SecAgentCheckModeField^ secAgentCheckMode, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQrySecAgentTradeInfo(SecAgentTradeInfoField^ secAgentTradeInfo, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQrySecAgentTradingAccount(TradingAccountField^ tradingAccount, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQrySettlementInfo(SettlementInfoField^ settlementInfo, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQrySettlementInfoConfirm(SettlementInfoConfirmField^ settlementInfoConfirm, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryTrade(TradeField^ trade, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryTradingAccount(TradingAccountField^ tradingAccount, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryTradingCode(TradingCodeField^ tradingCode, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryTradingNotice(TradingNoticeField^ tradingNotice, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryTransferBank(TransferBankField^ transferBank, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQryTransferSerial(TransferSerialField^ transferSerial, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQueryBankAccountMoneyByFuture(ReqQueryAccountField^ reqQueryAccount, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQueryCFMMCTradingAccountToken(QueryCFMMCTradingAccountTokenField^ queryCFMMCTradingAccountToken, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQueryMaxOrderVolume(QueryMaxOrderVolumeField^ queryMaxOrderVolume, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQuoteAction(InputQuoteActionField^ inputQuoteAction, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspQuoteInsert(InputQuoteField^ inputQuote, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspRemoveParkedOrder(RemoveParkedOrderField^ removeParkedOrder, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspRemoveParkedOrderAction(RemoveParkedOrderActionField^ removeParkedOrderAction, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspSettlementInfoConfirm(SettlementInfoConfirmField^ settlementInfoConfirm, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspSubForQuoteRsp(SpecificInstrumentField^ specificInstrument, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspSubMarketData(SpecificInstrumentField^ specificInstrument, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspTradingAccountPasswordUpdate(TradingAccountPasswordUpdateField^ tradingAccountPasswordUpdate, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspUnSubForQuoteRsp(SpecificInstrumentField^ specificInstrument, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspUnSubMarketData(SpecificInstrumentField^ specificInstrument, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspUserAuthMethod(RspUserAuthMethodField^ rspUserAuthMethod, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspUserLogin(RspUserLoginField^ rspUserLogin, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspUserLogout(UserLogoutField^ userLogout, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRspUserPasswordUpdate(UserPasswordUpdateField^ userPasswordUpdate, RspInfoField^ rspInfo, int requestID, bool isLast);
        public delegate void OnRtnBulletin(BulletinField^ bulletin);
        public delegate void OnRtnCancelAccountByBank(CancelAccountField^ cancelAccount);
        public delegate void OnRtnCFMMCTradingAccountToken(CFMMCTradingAccountTokenField^ cFMMCTradingAccountToken);
        public delegate void OnRtnChangeAccountByBank(ChangeAccountField^ changeAccount);
        public delegate void OnRtnCombAction(CombActionField^ combAction);
        public delegate void OnRtnDepthMarketData(DepthMarketDataField^ depthMarketData);
        public delegate void OnRtnErrorConditionalOrder(ErrorConditionalOrderField^ errorConditionalOrder);
        public delegate void OnRtnExecOrder(ExecOrderField^ execOrder);
        public delegate void OnRtnForQuoteRsp(ForQuoteRspField^ forQuoteRsp);
        public delegate void OnRtnFromBankToFutureByBank(RspTransferField^ rspTransfer);
        public delegate void OnRtnFromBankToFutureByFuture(RspTransferField^ rspTransfer);
        public delegate void OnRtnFromFutureToBankByBank(RspTransferField^ rspTransfer);
        public delegate void OnRtnFromFutureToBankByFuture(RspTransferField^ rspTransfer);
        public delegate void OnRtnInstrumentStatus(InstrumentStatusField^ instrumentStatus);
        public delegate void OnRtnOpenAccountByBank(OpenAccountField^ openAccount);
        public delegate void OnRtnOptionSelfClose(OptionSelfCloseField^ optionSelfClose);
        public delegate void OnRtnOrder(OrderField^ order);
        public delegate void OnRtnQueryBankBalanceByFuture(NotifyQueryAccountField^ notifyQueryAccount);
        public delegate void OnRtnQuote(QuoteField^ quote);
        public delegate void OnRtnRepealFromBankToFutureByBank(RspRepealField^ rspRepeal);
        public delegate void OnRtnRepealFromBankToFutureByFuture(RspRepealField^ rspRepeal);
        public delegate void OnRtnRepealFromBankToFutureByFutureManual(RspRepealField^ rspRepeal);
        public delegate void OnRtnRepealFromFutureToBankByBank(RspRepealField^ rspRepeal);
        public delegate void OnRtnRepealFromFutureToBankByFuture(RspRepealField^ rspRepeal);
        public delegate void OnRtnRepealFromFutureToBankByFutureManual(RspRepealField^ rspRepeal);
        public delegate void OnRtnTrade(TradeField^ trade);
        public delegate void OnRtnTradingNotice(TradingNoticeInfoField^ tradingNoticeInfo);
    }
}
