#pragma once
#include "ThostFtdcTraderApi.h"
#include "_typedefs.g.h"

class TraderSpi : public CThostFtdcTraderSpi
{
public:
#pragma region
    _typedefs::OnFrontConnected OnFrontConnectedCallback = __nullptr;
    _typedefs::OnFrontDisconnected OnFrontDisconnectedCallback = __nullptr;
    _typedefs::OnHeartBeatWarning OnHeartBeatWarningCallback = __nullptr;
    _typedefs::OnRspAuthenticate OnRspAuthenticateCallback = __nullptr;
    _typedefs::OnRspUserLogin OnRspUserLoginCallback = __nullptr;
    _typedefs::OnRspUserLogout OnRspUserLogoutCallback = __nullptr;
    _typedefs::OnRspUserPasswordUpdate OnRspUserPasswordUpdateCallback = __nullptr;
    _typedefs::OnRspTradingAccountPasswordUpdate OnRspTradingAccountPasswordUpdateCallback = __nullptr;
    _typedefs::OnRspUserAuthMethod OnRspUserAuthMethodCallback = __nullptr;
    _typedefs::OnRspGenUserCaptcha OnRspGenUserCaptchaCallback = __nullptr;
    _typedefs::OnRspGenUserText OnRspGenUserTextCallback = __nullptr;
    _typedefs::OnRspOrderInsert OnRspOrderInsertCallback = __nullptr;
    _typedefs::OnRspParkedOrderInsert OnRspParkedOrderInsertCallback = __nullptr;
    _typedefs::OnRspParkedOrderAction OnRspParkedOrderActionCallback = __nullptr;
    _typedefs::OnRspOrderAction OnRspOrderActionCallback = __nullptr;
    _typedefs::OnRspQueryMaxOrderVolume OnRspQueryMaxOrderVolumeCallback = __nullptr;
    _typedefs::OnRspSettlementInfoConfirm OnRspSettlementInfoConfirmCallback = __nullptr;
    _typedefs::OnRspRemoveParkedOrder OnRspRemoveParkedOrderCallback = __nullptr;
    _typedefs::OnRspRemoveParkedOrderAction OnRspRemoveParkedOrderActionCallback = __nullptr;
    _typedefs::OnRspExecOrderInsert OnRspExecOrderInsertCallback = __nullptr;
    _typedefs::OnRspExecOrderAction OnRspExecOrderActionCallback = __nullptr;
    _typedefs::OnRspForQuoteInsert OnRspForQuoteInsertCallback = __nullptr;
    _typedefs::OnRspQuoteInsert OnRspQuoteInsertCallback = __nullptr;
    _typedefs::OnRspQuoteAction OnRspQuoteActionCallback = __nullptr;
    _typedefs::OnRspBatchOrderAction OnRspBatchOrderActionCallback = __nullptr;
    _typedefs::OnRspOptionSelfCloseInsert OnRspOptionSelfCloseInsertCallback = __nullptr;
    _typedefs::OnRspOptionSelfCloseAction OnRspOptionSelfCloseActionCallback = __nullptr;
    _typedefs::OnRspCombActionInsert OnRspCombActionInsertCallback = __nullptr;
    _typedefs::OnRspQryOrder OnRspQryOrderCallback = __nullptr;
    _typedefs::OnRspQryTrade OnRspQryTradeCallback = __nullptr;
    _typedefs::OnRspQryInvestorPosition OnRspQryInvestorPositionCallback = __nullptr;
    _typedefs::OnRspQryTradingAccount OnRspQryTradingAccountCallback = __nullptr;
    _typedefs::OnRspQryInvestor OnRspQryInvestorCallback = __nullptr;
    _typedefs::OnRspQryTradingCode OnRspQryTradingCodeCallback = __nullptr;
    _typedefs::OnRspQryInstrumentMarginRate OnRspQryInstrumentMarginRateCallback = __nullptr;
    _typedefs::OnRspQryInstrumentCommissionRate OnRspQryInstrumentCommissionRateCallback = __nullptr;
    _typedefs::OnRspQryExchange OnRspQryExchangeCallback = __nullptr;
    _typedefs::OnRspQryProduct OnRspQryProductCallback = __nullptr;
    _typedefs::OnRspQryInstrument OnRspQryInstrumentCallback = __nullptr;
    _typedefs::OnRspQryDepthMarketData OnRspQryDepthMarketDataCallback = __nullptr;
    _typedefs::OnRspQrySettlementInfo OnRspQrySettlementInfoCallback = __nullptr;
    _typedefs::OnRspQryTransferBank OnRspQryTransferBankCallback = __nullptr;
    _typedefs::OnRspQryInvestorPositionDetail OnRspQryInvestorPositionDetailCallback = __nullptr;
    _typedefs::OnRspQryNotice OnRspQryNoticeCallback = __nullptr;
    _typedefs::OnRspQrySettlementInfoConfirm OnRspQrySettlementInfoConfirmCallback = __nullptr;
    _typedefs::OnRspQryInvestorPositionCombineDetail OnRspQryInvestorPositionCombineDetailCallback = __nullptr;
    _typedefs::OnRspQryCFMMCTradingAccountKey OnRspQryCFMMCTradingAccountKeyCallback = __nullptr;
    _typedefs::OnRspQryEWarrantOffset OnRspQryEWarrantOffsetCallback = __nullptr;
    _typedefs::OnRspQryInvestorProductGroupMargin OnRspQryInvestorProductGroupMarginCallback = __nullptr;
    _typedefs::OnRspQryExchangeMarginRate OnRspQryExchangeMarginRateCallback = __nullptr;
    _typedefs::OnRspQryExchangeMarginRateAdjust OnRspQryExchangeMarginRateAdjustCallback = __nullptr;
    _typedefs::OnRspQryExchangeRate OnRspQryExchangeRateCallback = __nullptr;
    _typedefs::OnRspQrySecAgentACIDMap OnRspQrySecAgentACIDMapCallback = __nullptr;
    _typedefs::OnRspQryProductExchRate OnRspQryProductExchRateCallback = __nullptr;
    _typedefs::OnRspQryProductGroup OnRspQryProductGroupCallback = __nullptr;
    _typedefs::OnRspQryMMInstrumentCommissionRate OnRspQryMMInstrumentCommissionRateCallback = __nullptr;
    _typedefs::OnRspQryMMOptionInstrCommRate OnRspQryMMOptionInstrCommRateCallback = __nullptr;
    _typedefs::OnRspQryInstrumentOrderCommRate OnRspQryInstrumentOrderCommRateCallback = __nullptr;
    _typedefs::OnRspQrySecAgentTradingAccount OnRspQrySecAgentTradingAccountCallback = __nullptr;
    _typedefs::OnRspQrySecAgentCheckMode OnRspQrySecAgentCheckModeCallback = __nullptr;
    _typedefs::OnRspQrySecAgentTradeInfo OnRspQrySecAgentTradeInfoCallback = __nullptr;
    _typedefs::OnRspQryOptionInstrTradeCost OnRspQryOptionInstrTradeCostCallback = __nullptr;
    _typedefs::OnRspQryOptionInstrCommRate OnRspQryOptionInstrCommRateCallback = __nullptr;
    _typedefs::OnRspQryExecOrder OnRspQryExecOrderCallback = __nullptr;
    _typedefs::OnRspQryForQuote OnRspQryForQuoteCallback = __nullptr;
    _typedefs::OnRspQryQuote OnRspQryQuoteCallback = __nullptr;
    _typedefs::OnRspQryOptionSelfClose OnRspQryOptionSelfCloseCallback = __nullptr;
    _typedefs::OnRspQryInvestUnit OnRspQryInvestUnitCallback = __nullptr;
    _typedefs::OnRspQryCombInstrumentGuard OnRspQryCombInstrumentGuardCallback = __nullptr;
    _typedefs::OnRspQryCombAction OnRspQryCombActionCallback = __nullptr;
    _typedefs::OnRspQryTransferSerial OnRspQryTransferSerialCallback = __nullptr;
    _typedefs::OnRspQryAccountregister OnRspQryAccountregisterCallback = __nullptr;
    _typedefs::OnRspError OnRspErrorCallback = __nullptr;
    _typedefs::OnRtnOrder OnRtnOrderCallback = __nullptr;
    _typedefs::OnRtnTrade OnRtnTradeCallback = __nullptr;
    _typedefs::OnErrRtnOrderInsert OnErrRtnOrderInsertCallback = __nullptr;
    _typedefs::OnErrRtnOrderAction OnErrRtnOrderActionCallback = __nullptr;
    _typedefs::OnRtnInstrumentStatus OnRtnInstrumentStatusCallback = __nullptr;
    _typedefs::OnRtnBulletin OnRtnBulletinCallback = __nullptr;
    _typedefs::OnRtnTradingNotice OnRtnTradingNoticeCallback = __nullptr;
    _typedefs::OnRtnErrorConditionalOrder OnRtnErrorConditionalOrderCallback = __nullptr;
    _typedefs::OnRtnExecOrder OnRtnExecOrderCallback = __nullptr;
    _typedefs::OnErrRtnExecOrderInsert OnErrRtnExecOrderInsertCallback = __nullptr;
    _typedefs::OnErrRtnExecOrderAction OnErrRtnExecOrderActionCallback = __nullptr;
    _typedefs::OnErrRtnForQuoteInsert OnErrRtnForQuoteInsertCallback = __nullptr;
    _typedefs::OnRtnQuote OnRtnQuoteCallback = __nullptr;
    _typedefs::OnErrRtnQuoteInsert OnErrRtnQuoteInsertCallback = __nullptr;
    _typedefs::OnErrRtnQuoteAction OnErrRtnQuoteActionCallback = __nullptr;
    _typedefs::OnRtnForQuoteRsp OnRtnForQuoteRspCallback = __nullptr;
    _typedefs::OnRtnCFMMCTradingAccountToken OnRtnCFMMCTradingAccountTokenCallback = __nullptr;
    _typedefs::OnErrRtnBatchOrderAction OnErrRtnBatchOrderActionCallback = __nullptr;
    _typedefs::OnRtnOptionSelfClose OnRtnOptionSelfCloseCallback = __nullptr;
    _typedefs::OnErrRtnOptionSelfCloseInsert OnErrRtnOptionSelfCloseInsertCallback = __nullptr;
    _typedefs::OnErrRtnOptionSelfCloseAction OnErrRtnOptionSelfCloseActionCallback = __nullptr;
    _typedefs::OnRtnCombAction OnRtnCombActionCallback = __nullptr;
    _typedefs::OnErrRtnCombActionInsert OnErrRtnCombActionInsertCallback = __nullptr;
    _typedefs::OnRspQryContractBank OnRspQryContractBankCallback = __nullptr;
    _typedefs::OnRspQryParkedOrder OnRspQryParkedOrderCallback = __nullptr;
    _typedefs::OnRspQryParkedOrderAction OnRspQryParkedOrderActionCallback = __nullptr;
    _typedefs::OnRspQryTradingNotice OnRspQryTradingNoticeCallback = __nullptr;
    _typedefs::OnRspQryBrokerTradingParams OnRspQryBrokerTradingParamsCallback = __nullptr;
    _typedefs::OnRspQryBrokerTradingAlgos OnRspQryBrokerTradingAlgosCallback = __nullptr;
    _typedefs::OnRspQueryCFMMCTradingAccountToken OnRspQueryCFMMCTradingAccountTokenCallback = __nullptr;
    _typedefs::OnRtnFromBankToFutureByBank OnRtnFromBankToFutureByBankCallback = __nullptr;
    _typedefs::OnRtnFromFutureToBankByBank OnRtnFromFutureToBankByBankCallback = __nullptr;
    _typedefs::OnRtnRepealFromBankToFutureByBank OnRtnRepealFromBankToFutureByBankCallback = __nullptr;
    _typedefs::OnRtnRepealFromFutureToBankByBank OnRtnRepealFromFutureToBankByBankCallback = __nullptr;
    _typedefs::OnRtnFromBankToFutureByFuture OnRtnFromBankToFutureByFutureCallback = __nullptr;
    _typedefs::OnRtnFromFutureToBankByFuture OnRtnFromFutureToBankByFutureCallback = __nullptr;
    _typedefs::OnRtnRepealFromBankToFutureByFutureManual OnRtnRepealFromBankToFutureByFutureManualCallback = __nullptr;
    _typedefs::OnRtnRepealFromFutureToBankByFutureManual OnRtnRepealFromFutureToBankByFutureManualCallback = __nullptr;
    _typedefs::OnRtnQueryBankBalanceByFuture OnRtnQueryBankBalanceByFutureCallback = __nullptr;
    _typedefs::OnErrRtnBankToFutureByFuture OnErrRtnBankToFutureByFutureCallback = __nullptr;
    _typedefs::OnErrRtnFutureToBankByFuture OnErrRtnFutureToBankByFutureCallback = __nullptr;
    _typedefs::OnErrRtnRepealBankToFutureByFutureManual OnErrRtnRepealBankToFutureByFutureManualCallback = __nullptr;
    _typedefs::OnErrRtnRepealFutureToBankByFutureManual OnErrRtnRepealFutureToBankByFutureManualCallback = __nullptr;
    _typedefs::OnErrRtnQueryBankBalanceByFuture OnErrRtnQueryBankBalanceByFutureCallback = __nullptr;
    _typedefs::OnRtnRepealFromBankToFutureByFuture OnRtnRepealFromBankToFutureByFutureCallback = __nullptr;
    _typedefs::OnRtnRepealFromFutureToBankByFuture OnRtnRepealFromFutureToBankByFutureCallback = __nullptr;
    _typedefs::OnRspFromBankToFutureByFuture OnRspFromBankToFutureByFutureCallback = __nullptr;
    _typedefs::OnRspFromFutureToBankByFuture OnRspFromFutureToBankByFutureCallback = __nullptr;
    _typedefs::OnRspQueryBankAccountMoneyByFuture OnRspQueryBankAccountMoneyByFutureCallback = __nullptr;
    _typedefs::OnRtnOpenAccountByBank OnRtnOpenAccountByBankCallback = __nullptr;
    _typedefs::OnRtnCancelAccountByBank OnRtnCancelAccountByBankCallback = __nullptr;
    _typedefs::OnRtnChangeAccountByBank OnRtnChangeAccountByBankCallback = __nullptr;
#pragma endregion

#pragma region
    void OnFrontConnected();
    void OnFrontDisconnected(int nReason);
    void OnHeartBeatWarning(int nTimeLapse);
    void OnRspAuthenticate(CThostFtdcRspAuthenticateField* pRspAuthenticateField, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspUserLogin(CThostFtdcRspUserLoginField* pRspUserLogin, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspUserLogout(CThostFtdcUserLogoutField* pUserLogout, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspUserPasswordUpdate(CThostFtdcUserPasswordUpdateField* pUserPasswordUpdate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspTradingAccountPasswordUpdate(CThostFtdcTradingAccountPasswordUpdateField* pTradingAccountPasswordUpdate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspUserAuthMethod(CThostFtdcRspUserAuthMethodField* pRspUserAuthMethod, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspGenUserCaptcha(CThostFtdcRspGenUserCaptchaField* pRspGenUserCaptcha, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspGenUserText(CThostFtdcRspGenUserTextField* pRspGenUserText, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspOrderInsert(CThostFtdcInputOrderField* pInputOrder, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspParkedOrderInsert(CThostFtdcParkedOrderField* pParkedOrder, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspParkedOrderAction(CThostFtdcParkedOrderActionField* pParkedOrderAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspOrderAction(CThostFtdcInputOrderActionField* pInputOrderAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQueryMaxOrderVolume(CThostFtdcQueryMaxOrderVolumeField* pQueryMaxOrderVolume, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspSettlementInfoConfirm(CThostFtdcSettlementInfoConfirmField* pSettlementInfoConfirm, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspRemoveParkedOrder(CThostFtdcRemoveParkedOrderField* pRemoveParkedOrder, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspRemoveParkedOrderAction(CThostFtdcRemoveParkedOrderActionField* pRemoveParkedOrderAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspExecOrderInsert(CThostFtdcInputExecOrderField* pInputExecOrder, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspExecOrderAction(CThostFtdcInputExecOrderActionField* pInputExecOrderAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspForQuoteInsert(CThostFtdcInputForQuoteField* pInputForQuote, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQuoteInsert(CThostFtdcInputQuoteField* pInputQuote, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQuoteAction(CThostFtdcInputQuoteActionField* pInputQuoteAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspBatchOrderAction(CThostFtdcInputBatchOrderActionField* pInputBatchOrderAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspOptionSelfCloseInsert(CThostFtdcInputOptionSelfCloseField* pInputOptionSelfClose, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspOptionSelfCloseAction(CThostFtdcInputOptionSelfCloseActionField* pInputOptionSelfCloseAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspCombActionInsert(CThostFtdcInputCombActionField* pInputCombAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryOrder(CThostFtdcOrderField* pOrder, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryTrade(CThostFtdcTradeField* pTrade, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryInvestorPosition(CThostFtdcInvestorPositionField* pInvestorPosition, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryTradingAccount(CThostFtdcTradingAccountField* pTradingAccount, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryInvestor(CThostFtdcInvestorField* pInvestor, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryTradingCode(CThostFtdcTradingCodeField* pTradingCode, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryInstrumentMarginRate(CThostFtdcInstrumentMarginRateField* pInstrumentMarginRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryInstrumentCommissionRate(CThostFtdcInstrumentCommissionRateField* pInstrumentCommissionRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryExchange(CThostFtdcExchangeField* pExchange, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryProduct(CThostFtdcProductField* pProduct, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryInstrument(CThostFtdcInstrumentField* pInstrument, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryDepthMarketData(CThostFtdcDepthMarketDataField* pDepthMarketData, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQrySettlementInfo(CThostFtdcSettlementInfoField* pSettlementInfo, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryTransferBank(CThostFtdcTransferBankField* pTransferBank, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryInvestorPositionDetail(CThostFtdcInvestorPositionDetailField* pInvestorPositionDetail, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryNotice(CThostFtdcNoticeField* pNotice, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQrySettlementInfoConfirm(CThostFtdcSettlementInfoConfirmField* pSettlementInfoConfirm, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryInvestorPositionCombineDetail(CThostFtdcInvestorPositionCombineDetailField* pInvestorPositionCombineDetail, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryCFMMCTradingAccountKey(CThostFtdcCFMMCTradingAccountKeyField* pCFMMCTradingAccountKey, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryEWarrantOffset(CThostFtdcEWarrantOffsetField* pEWarrantOffset, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryInvestorProductGroupMargin(CThostFtdcInvestorProductGroupMarginField* pInvestorProductGroupMargin, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryExchangeMarginRate(CThostFtdcExchangeMarginRateField* pExchangeMarginRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryExchangeMarginRateAdjust(CThostFtdcExchangeMarginRateAdjustField* pExchangeMarginRateAdjust, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryExchangeRate(CThostFtdcExchangeRateField* pExchangeRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQrySecAgentACIDMap(CThostFtdcSecAgentACIDMapField* pSecAgentACIDMap, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryProductExchRate(CThostFtdcProductExchRateField* pProductExchRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryProductGroup(CThostFtdcProductGroupField* pProductGroup, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryMMInstrumentCommissionRate(CThostFtdcMMInstrumentCommissionRateField* pMMInstrumentCommissionRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryMMOptionInstrCommRate(CThostFtdcMMOptionInstrCommRateField* pMMOptionInstrCommRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryInstrumentOrderCommRate(CThostFtdcInstrumentOrderCommRateField* pInstrumentOrderCommRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQrySecAgentTradingAccount(CThostFtdcTradingAccountField* pTradingAccount, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQrySecAgentCheckMode(CThostFtdcSecAgentCheckModeField* pSecAgentCheckMode, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQrySecAgentTradeInfo(CThostFtdcSecAgentTradeInfoField* pSecAgentTradeInfo, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryOptionInstrTradeCost(CThostFtdcOptionInstrTradeCostField* pOptionInstrTradeCost, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryOptionInstrCommRate(CThostFtdcOptionInstrCommRateField* pOptionInstrCommRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryExecOrder(CThostFtdcExecOrderField* pExecOrder, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryForQuote(CThostFtdcForQuoteField* pForQuote, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryQuote(CThostFtdcQuoteField* pQuote, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryOptionSelfClose(CThostFtdcOptionSelfCloseField* pOptionSelfClose, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryInvestUnit(CThostFtdcInvestUnitField* pInvestUnit, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryCombInstrumentGuard(CThostFtdcCombInstrumentGuardField* pCombInstrumentGuard, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryCombAction(CThostFtdcCombActionField* pCombAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryTransferSerial(CThostFtdcTransferSerialField* pTransferSerial, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryAccountregister(CThostFtdcAccountregisterField* pAccountregister, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspError(CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRtnOrder(CThostFtdcOrderField* pOrder);
    void OnRtnTrade(CThostFtdcTradeField* pTrade);
    void OnErrRtnOrderInsert(CThostFtdcInputOrderField* pInputOrder, CThostFtdcRspInfoField* pRspInfo);
    void OnErrRtnOrderAction(CThostFtdcOrderActionField* pOrderAction, CThostFtdcRspInfoField* pRspInfo);
    void OnRtnInstrumentStatus(CThostFtdcInstrumentStatusField* pInstrumentStatus);
    void OnRtnBulletin(CThostFtdcBulletinField* pBulletin);
    void OnRtnTradingNotice(CThostFtdcTradingNoticeInfoField* pTradingNoticeInfo);
    void OnRtnErrorConditionalOrder(CThostFtdcErrorConditionalOrderField* pErrorConditionalOrder);
    void OnRtnExecOrder(CThostFtdcExecOrderField* pExecOrder);
    void OnErrRtnExecOrderInsert(CThostFtdcInputExecOrderField* pInputExecOrder, CThostFtdcRspInfoField* pRspInfo);
    void OnErrRtnExecOrderAction(CThostFtdcExecOrderActionField* pExecOrderAction, CThostFtdcRspInfoField* pRspInfo);
    void OnErrRtnForQuoteInsert(CThostFtdcInputForQuoteField* pInputForQuote, CThostFtdcRspInfoField* pRspInfo);
    void OnRtnQuote(CThostFtdcQuoteField* pQuote);
    void OnErrRtnQuoteInsert(CThostFtdcInputQuoteField* pInputQuote, CThostFtdcRspInfoField* pRspInfo);
    void OnErrRtnQuoteAction(CThostFtdcQuoteActionField* pQuoteAction, CThostFtdcRspInfoField* pRspInfo);
    void OnRtnForQuoteRsp(CThostFtdcForQuoteRspField* pForQuoteRsp);
    void OnRtnCFMMCTradingAccountToken(CThostFtdcCFMMCTradingAccountTokenField* pCFMMCTradingAccountToken);
    void OnErrRtnBatchOrderAction(CThostFtdcBatchOrderActionField* pBatchOrderAction, CThostFtdcRspInfoField* pRspInfo);
    void OnRtnOptionSelfClose(CThostFtdcOptionSelfCloseField* pOptionSelfClose);
    void OnErrRtnOptionSelfCloseInsert(CThostFtdcInputOptionSelfCloseField* pInputOptionSelfClose, CThostFtdcRspInfoField* pRspInfo);
    void OnErrRtnOptionSelfCloseAction(CThostFtdcOptionSelfCloseActionField* pOptionSelfCloseAction, CThostFtdcRspInfoField* pRspInfo);
    void OnRtnCombAction(CThostFtdcCombActionField* pCombAction);
    void OnErrRtnCombActionInsert(CThostFtdcInputCombActionField* pInputCombAction, CThostFtdcRspInfoField* pRspInfo);
    void OnRspQryContractBank(CThostFtdcContractBankField* pContractBank, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryParkedOrder(CThostFtdcParkedOrderField* pParkedOrder, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryParkedOrderAction(CThostFtdcParkedOrderActionField* pParkedOrderAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryTradingNotice(CThostFtdcTradingNoticeField* pTradingNotice, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryBrokerTradingParams(CThostFtdcBrokerTradingParamsField* pBrokerTradingParams, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQryBrokerTradingAlgos(CThostFtdcBrokerTradingAlgosField* pBrokerTradingAlgos, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQueryCFMMCTradingAccountToken(CThostFtdcQueryCFMMCTradingAccountTokenField* pQueryCFMMCTradingAccountToken, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRtnFromBankToFutureByBank(CThostFtdcRspTransferField* pRspTransfer);
    void OnRtnFromFutureToBankByBank(CThostFtdcRspTransferField* pRspTransfer);
    void OnRtnRepealFromBankToFutureByBank(CThostFtdcRspRepealField* pRspRepeal);
    void OnRtnRepealFromFutureToBankByBank(CThostFtdcRspRepealField* pRspRepeal);
    void OnRtnFromBankToFutureByFuture(CThostFtdcRspTransferField* pRspTransfer);
    void OnRtnFromFutureToBankByFuture(CThostFtdcRspTransferField* pRspTransfer);
    void OnRtnRepealFromBankToFutureByFutureManual(CThostFtdcRspRepealField* pRspRepeal);
    void OnRtnRepealFromFutureToBankByFutureManual(CThostFtdcRspRepealField* pRspRepeal);
    void OnRtnQueryBankBalanceByFuture(CThostFtdcNotifyQueryAccountField* pNotifyQueryAccount);
    void OnErrRtnBankToFutureByFuture(CThostFtdcReqTransferField* pReqTransfer, CThostFtdcRspInfoField* pRspInfo);
    void OnErrRtnFutureToBankByFuture(CThostFtdcReqTransferField* pReqTransfer, CThostFtdcRspInfoField* pRspInfo);
    void OnErrRtnRepealBankToFutureByFutureManual(CThostFtdcReqRepealField* pReqRepeal, CThostFtdcRspInfoField* pRspInfo);
    void OnErrRtnRepealFutureToBankByFutureManual(CThostFtdcReqRepealField* pReqRepeal, CThostFtdcRspInfoField* pRspInfo);
    void OnErrRtnQueryBankBalanceByFuture(CThostFtdcReqQueryAccountField* pReqQueryAccount, CThostFtdcRspInfoField* pRspInfo);
    void OnRtnRepealFromBankToFutureByFuture(CThostFtdcRspRepealField* pRspRepeal);
    void OnRtnRepealFromFutureToBankByFuture(CThostFtdcRspRepealField* pRspRepeal);
    void OnRspFromBankToFutureByFuture(CThostFtdcReqTransferField* pReqTransfer, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspFromFutureToBankByFuture(CThostFtdcReqTransferField* pReqTransfer, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRspQueryBankAccountMoneyByFuture(CThostFtdcReqQueryAccountField* pReqQueryAccount, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast);
    void OnRtnOpenAccountByBank(CThostFtdcOpenAccountField* pOpenAccount);
    void OnRtnCancelAccountByBank(CThostFtdcCancelAccountField* pCancelAccount);
    void OnRtnChangeAccountByBank(CThostFtdcChangeAccountField* pChangeAccount);
#pragma endregion
};
